database_1:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

database_2:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /views/
      suffix: .jsp